### TODO#12
### Completa los ... de las siguientes peticiones por orden,
### para probar el API con el plugin REST CLIENT de VsCode

### Create user

POST http://localhost:8080/api/users
Content-Type: application/json

{
   "name": "Telmo",
  "email": "telmo@email.com",
  "role": "USER",
  "password": "aaaaaaaA1"}

### Login

POST http://localhost:8080/api/users/me/session
Content-Type: application/json
{
  "email": "telmo@email.com",
  "password": "aaaaaaaA1"
}

### Profile

GET http://localhost:8080/api/users/me
Cookie: session= (añadir al usar el postman)

